version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: task_management_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d task_management_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://username:password@postgres:5432/task_management_db
      - JWT_SECRET=your-secret-key
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
