[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run db:migrate && npx prisma db seed && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
numReplicas = 1

[phases.setup]
nixPkgs = ["nodejs", "npm"] 