[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "sh -c 'npm run db:migrate && npx prisma generate && NODE_ENV=production npx ts-node --compiler-options {\\\"module\\\":\\\"CommonJS\\\"} prisma/seed.ts && npm run start'"
healthcheckPath = "/api/health"
healthcheckTimeout = 180
healthcheckInterval = 15
restartPolicyType = "on_failure"
numReplicas = 1

[phases.setup]
nixPkgs = ["nodejs", "npm"] 